# Generated by Django 4.1.13 on 2023-11-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postgres_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scores",
            name="attempts_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scores",
            name="quiz_attempted",
            field=models.BooleanField(default=False),
        ),
    ]
